qmad.gap=new Object();qmad.bvis+="qm_gap_a(b.cdiv);";qmad.bhide+="qm_gap_a(a,1);";qmad.br_navigator=navigator.userAgent.indexOf("Netscape")+1;qmad.br_version=parseFloat(navigator.vendorSub);qmad.br_oldnav=qmad.br_navigator&&qmad.br_version<7.1;qmad.br_ie=window.showHelp;qmad.br_mac=navigator.userAgent.indexOf("Mac")+1;qmad.br_old_safari=navigator.userAgent.indexOf("afari")+1&&!window.XMLHttpRequest;qmad.gap_off=(qmad.br_ie&&qmad.br_mac)||qmad.br_old_safari||qmad.br_oldnav;;function qm_gap_a(a,hide){
    if((a.style.visibility=="inherit"&&!hide)||(qmad.gap_off))return;var ss;if(!a.settingsid){var v=a;while((v=v.parentNode)){
    if(v.className.indexOf("qmmc")+1){a.settingsid=v.id;break;}}}ss=qmad[a.settingsid];if(!ss)return;if(!ss.gap_increment)return;if(hide&&ss.gap_hide_off)return;var b=new Object();b.obj=a;b.inc=ss.gap_increment;if(hide&&ss.gap_hide_increment)b.inc=ss.gap_hide_increment;b.start_size=ss.gap_start_size;b.mid_size=ss.gap_max_size;b.end_size=ss.gap_end_size;b.hide_size=ss.gap_hide_size;b.cur_size=b.start_size;if(hide){
    if(b.hide_size<b.end_size)b.inc=-b.inc;b.cur_size=b.end_size;x2("qmfv",a,1);}b.applytop=ss.gap_apply_top;b.applybottom=ss.gap_apply_bottom;if(b.start_size<0||b.hide_size<0){b.reset=true;qm_gap_container_zero(a,"0px");}a.isrun=true;var id=qm_gap_am(b,hide);b.id=id;if(!hide)qm_gap_set_tags(a,id,"init");qm_gap_ai(id,hide);};function qm_gap_container_zero(a,val){a.style.paddingTop=val;a.style.paddingBottom=val;a.style.borderTopWidth=val;a.style.borderBottomWidth=val;};function qm_gap_ai(id,hide){var a=qmad.gap["_"+id];if(!a)return;if(hide){
    if(Math.abs(a.cur_size)<Math.abs(a.hide_size-a.inc)){qm_gap_set_tags(a.obj,id,"inc",1);a.timer=setTimeout("qm_gap_ai("+id+","+hide+")",10);}else {x2("qmfv",a.obj);qm_gap_set_tags(a.obj,id,"end");a.obj.isrun=false;}}else {
    if(!a.is_dec&&a.cur_size<(a.mid_size-a.inc)){
    if(a.reset&&a.obj.offsetHeight>0){qm_gap_container_zero(a.obj,"");a.reset=false;}qm_gap_set_tags(a.obj,id,"inc");a.timer=setTimeout("qm_gap_ai("+id+","+hide+")",10);return;}else  if(a.end_size<a.mid_size&&a.cur_size>(a.end_size+a.inc)){
    if(!a.is_dec){qm_gap_set_tags(a.obj,id,"spec");a.is_dec=true;}else qm_gap_set_tags(a.obj,id,"dec");a.timer=setTimeout("qm_gap_ai("+id+","+hide+")",10);}else {qm_gap_set_tags(a.obj,id,"end");if(document.createElementNS&&!a.firefoxfixed){a.firefoxfixed=true;var p=document.createElement("span");p.style.display="block";p.style.position="absolute";a.obj.appendChild(p);}qm_gap_container_zero(a.obj,"");a.obj.isrun=false;qmad.gap["_"+id]=null;}}};function qm_gap_set_tags(a,id,type){var t,tt,tv;var s=qmad.gap["_"+id];var ach=a.childNodes;for(var i=0;i<ach.length;i++){var ab=0;var at=0;if(ach[i].tagName=="A"){
    if(type=="spec"){
    if(s.applytop)ach[i].style.marginTop=s.mid_size+"px";if(s.applybottom)ach[i].style.marginBottom=s.mid_size+"px";}else  if(type=="inc"){
    if(s.applytop){s.cur_size=parseFloat(ach[i].style.marginTop)+s.inc;ach[i].style.marginTop=s.cur_size+"px";}if(s.applybottom){s.cur_size=parseFloat(ach[i].style.marginBottom)+s.inc;ach[i].style.marginBottom=s.cur_size+"px";}}else  if(type=="dec"){
    if(s.applytop){s.cur_size=parseFloat(ach[i].style.marginTop)-s.inc;ach[i].style.marginTop=s.cur_size+"px";}if(s.applybottom){s.cur_size=parseFloat(ach[i].style.marginBottom)-s.inc;ach[i].style.marginBottom=s.cur_size+"px";}}else  if(type=="init"){
    if(s.start_size<0||s.hide_size<0){ach[i].style.position="relative";if(window.showHelp){var tval=ach[i].parentNode.currentStyle.backgroundImage;if(!tval||tval=="none")ach[i].parentNode.style.backgroundImage="url(iefix.gif)";}}if(s.applytop)ach[i].style.marginTop=s.start_size+"px";if(s.applybottom)ach[i].style.marginBottom=s.start_size+"px";}else  if(type=="end"){
    if(s.applytop)ach[i].style.marginTop=s.end_size+"px";if(s.applybottom)ach[i].style.marginBottom=s.end_size+"px";}}}};function qm_gap_am(obj,hide){var k;for(k in qmad.gap){
    if(qmad.gap[k]&&obj.obj==qmad.gap[k].obj){
    if(qmad.gap[k].timer){clearTimeout(qmad.gap[k].timer);qmad.gap[k].timer=null;}qmad.gap[k]=null;}}var i=0;while(qmad.gap["_"+i])i++;qmad.gap["_"+i]=obj;return i;}