# MySQL-Front 3.2  (Build 6.14)

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES 'latin1' */;

# Host: localhost    Database: bd_intranet
# ------------------------------------------------------
# Server version 5.0.22-community-nt-log

#
# Table structure for table modulo
#

DROP TABLE IF EXISTS `modulo`;
CREATE TABLE `modulo` (
  `Id` int(11) NOT NULL auto_increment,
  `id_grupo` int(11) NOT NULL default '0',
  `sareta_id_modulo` int(11) default NULL,
  `sareta_principal` char(1) collate latin1_spanish_ci default 'N',
  `tipo_menu` char(1) collate latin1_spanish_ci NOT NULL default '0',
  `identificacion` varchar(30) collate latin1_spanish_ci default NULL,
  `nombre` varchar(60) collate latin1_spanish_ci NOT NULL,
  `pagina` varchar(200) collate latin1_spanish_ci NOT NULL default '',
  `variables` varchar(80) collate latin1_spanish_ci default NULL,
  `target` varchar(30) collate latin1_spanish_ci default 'frame_principal',
  `menu` char(1) collate latin1_spanish_ci NOT NULL default 'Y',
  `publico` char(1) collate latin1_spanish_ci NOT NULL default 'N',
  `acceso_root` char(1) collate latin1_spanish_ci NOT NULL default 'N',
  `obs` varchar(200) collate latin1_spanish_ci default NULL,
  `ultimo_usuario` varchar(30) collate latin1_spanish_ci NOT NULL default '',
  `fecha_actualizacion` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `div` varchar(30) collate latin1_spanish_ci default NULL,
  PRIMARY KEY  (`Id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci;

#
# Dumping data for table modulo
#

INSERT INTO `modulo` VALUES (3,1,-1,'N','0','intaddperfil','Registrar Perfil','./public/intranet/gestion_usuario/perfiles/intranet_addperfil.php','','frame_principal','Y','N','N','Modulo de registro de perfil','','2008-08-19 14:40:39',NULL);
INSERT INTO `modulo` VALUES (5,29,-1,'N','0','intaddmod','Registrar Módulo','./public/intranet/administracion_sistema/modulos/intranet_addmodulo.php','','frame_principal','Y','N','N','Modulo de registro de modulos','','2008-08-12 14:55:04',NULL);
INSERT INTO `modulo` VALUES (6,29,-1,'N','0','addperfilgrupo','Asignar Grupo','./public/intranet/gestion_usuario/perfiles/intranet_addperfilgrupo.php','','frame_principal','Y','N','N','Modulo de asignacion de grupo','','2008-07-04 19:50:30',NULL);
INSERT INTO `modulo` VALUES (7,29,-1,'N','0','addperfilmodulo','Asignar Módulo','./public/intranet/gestion_usuario/perfiles/intranet_addperfilmodulo.php','','frame_principal','Y','N','N','Modulo de asignacion de modulo','','2008-07-04 20:07:52',NULL);
INSERT INTO `modulo` VALUES (9,1,-1,'N','0','intconsusuario','Listado Usuarios','./public/intranet/gestion_usuario/usuarios/intranet_consusuarios.php','','frame_principal','Y','N','N','Modulo de consulta de usuarios registrados','','2008-08-20 13:30:25',NULL);
INSERT INTO `modulo` VALUES (10,29,-1,'N','0','intconsmod','Listado Módulos','./public/intranet/administracion_sistema/modulos/intranet_consmodulos.php','','frame_principal','Y','N','N','Modulos Registrados','','2008-07-04 18:16:43',NULL);
INSERT INTO `modulo` VALUES (16,6,-1,'N','0','intconswallpaper','Listado de Fondos de Pantalla','./public/intranet/servicio/wallpaper/intranet_conswallpapers.php','','frame_principal','Y','N','N','Modulo de Administración de Wallpapers','','2008-08-27 10:21:03',NULL);
INSERT INTO `modulo` VALUES (17,29,-1,'N','0','intconsgrupo','Listado Grupos','./public/intranet/administracion_sistema/grupos/intranet_consgrupo.php','','frame_principal','Y','N','N','Modulo de consulta de modulos','','2008-08-14 10:54:23',NULL);
INSERT INTO `modulo` VALUES (18,1,-1,'N','0','intconsperfil','Listado Perfiles','./public/intranet/gestion_usuario/perfiles/intranet_consperfiles.php','','frame_principal','Y','N','N','Modulo de perfiles registrados','','2008-08-19 11:26:24',NULL);
INSERT INTO `modulo` VALUES (34,8,-1,'N','0','intaddmusica','Listado de Música','intranet_addmusica.php','','frame_principal','Y','N','N','Modulo para el registro de musica','','2008-08-19 09:06:47',NULL);
INSERT INTO `modulo` VALUES (36,8,-1,'N','0','intconsmusica','Registrar Música','intranet_consmusica.php','','frame_principal','Y','N','N','Modulo de consulta de musica registrada','','2008-08-19 08:58:10',NULL);
INSERT INTO `modulo` VALUES (43,1,-1,'N','0','intaddtipousuario','Registrar Tipo Usuario','./public/intranet/gestion_usuario/usuarios/intranet_addtipousuario.php','','frame_principal','Y','N','N','Modulo de registro de tipo usuario','','2008-08-26 10:05:33',NULL);
INSERT INTO `modulo` VALUES (47,6,-1,'N','0','intaddwallpaper','Registrar Fondo de Pantalla','./public/intranet/servicio/wallpaper/intranet_addwallpaper.php','','frame_principal','Y','N','N','Registrar Fondo','','2008-08-27 10:26:49',NULL);
INSERT INTO `modulo` VALUES (50,1,-1,'N','0','intaddusuario','Registrar Usuario','./public/intranet/gestion_usuario/usuarios/intranet_addusuario.php','','frame_principal','Y','N','N','Modulo de registro de usuarios','','2008-08-20 13:28:17',NULL);
INSERT INTO `modulo` VALUES (51,29,-1,'N','0','intaddgrupo','Registrar Grupo','./public/intranet/administracion_sistema/grupos/intranet_addgrupo.php','','frame_principal','Y','N','N','Modulo de registro de grupos','','2008-08-14 10:50:02',NULL);
INSERT INTO `modulo` VALUES (52,1,-1,'N','0','intadddivision','Registrar División','./public/intranet/gestion_usuario/division/intranet_adddivision.php','','frame_principal','Y','N','N','Modulo de registro de divisiones','','2008-08-19 10:58:52',NULL);
INSERT INTO `modulo` VALUES (54,1,-1,'N','0','intaddcuenta','Registrar Cuenta','./public/intranet/administracion_sistema/usuarios/intranet_addcuenta.php','','frame_principal','N','N','N','Modulo de registro de cuenta','','2008-08-19 08:48:43',NULL);
INSERT INTO `modulo` VALUES (59,20,-1,'N','0','intaddsoporte','Petición de Soporte','./public/intranet/servicio/soporte/intranet_addpeticionsoporte.php','','frame_principal','Y','N','N','Modulo de solución a soportes','','2008-09-03 12:38:42',NULL);
INSERT INTO `modulo` VALUES (60,20,-1,'N','0','intconspeticionpendiente','Peticiones Pendientes','intranet_conspeticionespendientes.php','','frame_principal','Y','N','N','','','2008-08-19 08:58:04',NULL);
INSERT INTO `modulo` VALUES (65,22,339,'N','1','saraddbanco','Registrar Banco','./contabilidad/mantenimiento/banco/sareta_addbanco.php','','frame_principal','Y','N','N','','','2008-07-04 22:20:50',NULL);
INSERT INTO `modulo` VALUES (66,28,339,'N','1','sarconsbanco','Consultar Bancos','./contabilidad/mantenimiento/banco/sareta_consbanco.php','','frame_principal','Y','N','N','Modulo de consulta de bancos','','2008-07-07 10:57:58',NULL);
INSERT INTO `modulo` VALUES (67,22,337,'N','1','saraddmoneda','Registrar Monedas','./recaudacion/mantenimiento/moneda/sareta_addmoneda.php','','frame_principal','Y','N','N','Modulo de mantenimiento de monedas','','2008-07-04 22:21:39',NULL);
INSERT INTO `modulo` VALUES (68,28,337,'N','1','sarconsmoneda','Consultar Monedas','./recaudacion/mantenimiento/moneda/sareta_consmoneda.php','','frame_principal','Y','N','N','Modulo de consulta de monedas','','2008-07-04 22:23:54',NULL);
INSERT INTO `modulo` VALUES (72,28,64,'N','1','sarfrmmoneda','frm_list_monedas','./recaudacion/mantenimiento/moneda/sareta_frame_moneda.php','','frame_principal','N','N','N','Listado de Monedas','','2008-07-04 22:24:56',NULL);
INSERT INTO `modulo` VALUES (78,28,62,'N','1','sarfrmbanco','frm_list_banco','./contabilidad/mantenimiento/banco/sareta_frame_banco.php','','frame_principal','N','N','N','Modulo frame de consulta de bancos','','2008-07-07 10:57:46',NULL);
INSERT INTO `modulo` VALUES (91,22,337,'N','1','saraddbandera','Registrar Bandera','./recaudacion/mantenimiento/bandera/sareta_addbandera.php','','frame_principal','Y','N','N','Mantenimiento de banderas SARETA','','2008-07-04 22:25:19',NULL);
INSERT INTO `modulo` VALUES (93,22,338,'N','1','saradddelegacion','Registrar Delegacion','./administracion_general/mantenimiento/delegacion/sareta_adddelegacion.php','','frame_principal','Y','N','N','Mantenimiento de delegacion SARETA','','2008-07-07 09:26:05',NULL);
INSERT INTO `modulo` VALUES (94,28,337,'N','1','sarconsbandera','Consultar Banderas','./recaudacion/mantenimiento/bandera/sareta_consbanderas.php','','frame_principal','Y','N','N','Modulo de consulta de banderas','','2008-07-04 22:25:54',NULL);
INSERT INTO `modulo` VALUES (95,28,-1,'N','0','sarfrmbandera','frm_list_bandera','./recaudacion/mantenimiento/bandera/sareta_frame_banderas.php','','frame_principal','N','N','N','Modulo frame de consulta de banderas','','2008-07-04 22:26:30',NULL);
INSERT INTO `modulo` VALUES (96,22,337,'N','1','saraddtipotasa','Registrar Tipo de Tasa','./recaudacion/mantenimiento/tipo_tasa/sareta_addtipotasa.php','','frame_principal','Y','N','N','','','2008-07-04 22:26:49',NULL);
INSERT INTO `modulo` VALUES (97,28,337,'N','1','sarconstipotasa','Consultar Tasas','./recaudacion/mantenimiento/tipo_tasa/sareta_constipotasa.php','','frame_principal','Y','N','N','Modulo de consulta de tasas','','2008-07-04 22:27:05',NULL);
INSERT INTO `modulo` VALUES (99,28,-1,'N','0','sarfrmtipotasa','frm_list_tipotasa','./recaudacion/mantenimiento/tipo_tasa/sareta_frame_tipotasa.php','','frame_principal','N','N','N','Listado de tasas','','2008-07-04 22:27:35',NULL);
INSERT INTO `modulo` VALUES (101,22,337,'N','1','saraddformapago','Registrar Forma de Pago','./recaudacion/mantenimiento/forma_pago/sareta_addformapago.php','','frame_principal','Y','N','N','','','2008-07-04 22:27:52',NULL);
INSERT INTO `modulo` VALUES (102,28,337,'N','1','sarconsformapago','Consultar Forma de Pagos','./recaudacion/mantenimiento/forma_pago/sareta_consformapago.php','','frame_principal','Y','N','N','Modulo de consulta de formas de pago','','2008-07-04 22:29:14',NULL);
INSERT INTO `modulo` VALUES (103,28,-1,'N','0','sarfrmformapago','frm_list_forma_pago','./recaudacion/mantenimiento/forma_pago/sareta_frame_formapago.php','','frame_principal','N','N','N','Modulo frame de consulta de formas de pago','','2008-07-04 22:29:49',NULL);
INSERT INTO `modulo` VALUES (104,22,337,'N','1','saraddestado','Registrar Estado','./recaudacion/mantenimiento/estado/sareta_addestado.php','','frame_principal','Y','N','N','','','2008-07-04 22:29:59',NULL);
INSERT INTO `modulo` VALUES (105,28,337,'N','1','sarconsestado','Consultar Estados','./recaudacion/mantenimiento/estado/sareta_consestado.php','Modulo de Consulta de Estados Registrados en SARETA','frame_principal','Y','N','N','Modulos de consulta de estados','','2008-07-04 22:30:11',NULL);
INSERT INTO `modulo` VALUES (106,28,-1,'N','0','sarfrmestado','frm_list_estado','./recaudacion/mantenimiento/estado/sareta_frame_estado.php','','frame_principal','N','N','N','Modulo frame de consulta de estados','','2008-07-04 22:30:28',NULL);
INSERT INTO `modulo` VALUES (107,22,337,'N','1','saraddagencianaviera','Registrar Agencia Naviera','./recaudacion/mantenimiento/agencia_naviera/sareta_addagencianaviera.php','','frame_principal','Y','N','N','','','2008-07-07 13:26:21',NULL);
INSERT INTO `modulo` VALUES (108,30,-1,'N','0','sarimpmoneda','sar_imp_moneda','./recaudacion/mantenimiento/moneda/sareta_impmoneda.php','','frame_principal','N','N','N','Modulo de impresion de monedas','','2008-07-04 22:31:22',NULL);
INSERT INTO `modulo` VALUES (110,28,337,'N','1','sarconsagencianaviera','Consultar Agencias Nav.','./recaudacion/mantenimiento/agencia_naviera/sareta_consagencianaviera.php','','frame_principal','Y','N','N','Modulo de consulta de agencias navieras','','2008-07-04 22:31:33',NULL);
INSERT INTO `modulo` VALUES (112,22,337,'N','1','saraddtipoactividad','Registrar Tipo Actividad','./recaudacion/mantenimiento/tipo_actividad/sareta_addtipoactividad.php','','frame_principal','Y','N','N','','','2008-07-04 22:31:54',NULL);
INSERT INTO `modulo` VALUES (113,28,337,'N','1','sarconstipoactividad','Consultar Tipo Actividad','./recaudacion/mantenimiento/tipo_actividad/sareta_constipoactividad.php','','frame_principal','Y','N','N','Modulos de consulta de tipos de actividades','','2008-07-15 13:24:30',NULL);
INSERT INTO `modulo` VALUES (114,28,-1,'N','0','sarfrmtipoactividad','frm_list_tipoactividad','./recaudacion/mantenimiento/tipo_actividad/sareta_frame_tipoactividad.php','','frame_principal','N','N','N','Modulo frame de consulta de tipo de actividad','','2008-07-04 22:32:25',NULL);
INSERT INTO `modulo` VALUES (115,22,337,'N','1','saraddclasebuque','Registrar Clase de Buque','./recaudacion/mantenimiento/clase_buque/sareta_addclasebuque.php','','frame_principal','Y','N','N','','','2008-07-04 22:32:46',NULL);
INSERT INTO `modulo` VALUES (117,28,-1,'N','0','sarfrmclasebuque','frm_list_clasebuque','./recaudacion/mantenimiento/clase_buque/sareta_frame_clasebuque.php','','frame_principal','N','N','N','Modulo frame de consulta de clases de buques','','2008-07-04 22:33:02',NULL);
INSERT INTO `modulo` VALUES (119,22,337,'N','1','saraddtipodocumento','Registrar Tipo Documento','./recaudacion/mantenimiento/tipo_documento/sareta_addtipodocumento.php','','frame_principal','Y','N','N','','','2008-07-04 22:33:25',NULL);
INSERT INTO `modulo` VALUES (120,28,337,'N','1','sarconstipodocumento','Consultar Tipos de Documentos','./recaudacion/mantenimiento/tipo_documento/sareta_constipodocumento.php','','frame_principal','Y','N','N','Modulo de consulta de tipos de documentos','','2008-07-04 22:33:46',NULL);
INSERT INTO `modulo` VALUES (121,28,-1,'N','0','sarfrmtipodocumento','frm_list_tipodocumento','./recaudacion/mantenimiento/tipo_documento/sareta_frame_tipodocumento.php','','frame_principal','N','N','N','Modulo frame de consulta de tipos de documentos','','2008-07-04 22:34:10',NULL);
INSERT INTO `modulo` VALUES (122,30,64,'N','1','sarimpbandera','sar_imp_bandera','./recaudacion/mantenimiento/bandera/sareta_impbanderas.php','','frame_principal','N','N','N','Modulo de impresion PDF de banderas','','2008-07-04 22:34:31',NULL);
INSERT INTO `modulo` VALUES (123,30,64,'N','1','sarimptipoactividad','sar_imp_tipoactividad','./recaudacion/mantenimiento/tipo_actividad/sareta_imptipoactividad.php','','frame_principal','N','N','N','','','2008-07-04 22:34:57',NULL);
INSERT INTO `modulo` VALUES (124,30,64,'N','1','sarimpmoneda','sar_imp_moneda','./recaudacion/mantenimiento/moneda/sareta_impmoneda.php','','frame_principal','N','N','N','','','2008-07-04 22:36:23',NULL);
INSERT INTO `modulo` VALUES (126,30,64,'N','1','sarimpestado','sar_imp_estado','./recaudacion/mantenimiento/estado/sareta_impestado.php','','frame_principal','N','N','N','','','2008-07-04 22:36:30',NULL);
INSERT INTO `modulo` VALUES (127,20,-1,'N','0',NULL,'frm_list_peticionsoporte','frame_peticion_soporte.php','','frame_principal','N','N','N','','','2008-07-07 09:26:32',NULL);
INSERT INTO `modulo` VALUES (128,30,64,'N','1','sarimpformapago','sar_imp_formapago','./recaudacion/mantenimiento/forma_pago/sareta_impformapago.php','','frame_principal','N','N','N','','','2008-07-04 22:36:58',NULL);
INSERT INTO `modulo` VALUES (131,28,337,'N','1','sarconsclasebuque','Consultar Clase de Buque','./recaudacion/mantenimiento/clase_buque/sareta_consclasebuque.php','','frame_principal','Y','N','N','Modulo de consulta de clases de buques','','2008-07-04 22:37:49',NULL);
INSERT INTO `modulo` VALUES (134,22,337,'N','1','saraddbuque','Registrar Buque','./recaudacion/mantenimiento/buque/sareta_addbuque.php','','frame_principal','Y','N','N','','','2008-07-04 22:37:59',NULL);
INSERT INTO `modulo` VALUES (135,28,337,'N','1','sarconsbuque','Consultar Buques','./recaudacion/mantenimiento/buque/sareta_consbuque.php','','frame_principal','Y','N','N','Modulo de consulta de buques','','2008-07-04 22:38:12',NULL);
INSERT INTO `modulo` VALUES (136,28,-1,'N','0','sarfrmbuque','frm_list_buque','./recaudacion/mantenimiento/buque/sareta_frame_buque.php','','frame_principal','N','N','N','Modulo frane de consulta de buques','','2008-07-04 22:38:38',NULL);
INSERT INTO `modulo` VALUES (139,1,-1,'N','0','intaddcompania','Registrar Compañia','./public/intranet/administracion_sistema/compania/intranet_addcompania.php','','frame_principal','Y','N','N','Modulo para el registro de compañias','','2008-08-19 09:08:04',NULL);
INSERT INTO `modulo` VALUES (140,30,64,'N','1','sarimpagencianaviera','sar_imp_agencianaviera','./recaudacion/mantenimiento/agencia_naviera/sareta_impagencia_naviera.php','','frame_principal','N','N','N','','','2008-07-04 22:39:07',NULL);
INSERT INTO `modulo` VALUES (141,30,-1,'N','0','sarimptipodocumento','sareta_imptipodocumento','./recaudacion/mantenimiento/tipo_documento/sareta_imptipodocumento.php','','frame_principal','N','N','N','','','2008-07-04 22:39:18',NULL);
INSERT INTO `modulo` VALUES (142,1,-1,'N','0','intconscompania','Listado Compañias','./public/intranet/administracion_sistema/compania/intranet_conscompanias.php','','frame_principal','Y','N','N','Modulo de consulta de compañias registradas','','2008-08-19 09:00:31',NULL);
INSERT INTO `modulo` VALUES (144,30,-1,'N','0','sarimpclasebuque','sar_imp_clasebuque','./recaudacion/mantenimiento/clase_buque/sareta_impclasebuque.php','','frame_principal','N','N','N','','','2008-07-04 22:39:38',NULL);
INSERT INTO `modulo` VALUES (145,30,-1,'N','0','sarimptipotasa','sareta_imptipotasa','./recaudacion/mantenimiento/tipo_tasa/sareta_imptipotasa.php','','frame_principal','N','N','N','','','2008-07-15 14:40:45',NULL);
INSERT INTO `modulo` VALUES (155,22,337,'N','1','saraddley','Registrar Ley','./recaudacion/mantenimiento/ley/sareta_addley.php','','frame_principal','Y','N','N','','','2008-07-04 22:40:06',NULL);
INSERT INTO `modulo` VALUES (157,28,337,'N','1','sarconsley','Consultar Leyes','./recaudacion/mantenimiento/ley/sareta_consley.php','','frame_principal','Y','N','N','Modulo de consulta de leyes de faros y boyas','','2008-07-04 22:40:21',NULL);
INSERT INTO `modulo` VALUES (158,28,-1,'N','0','sarfrmley','frm_list_ley','./recaudacion/mantenimiento/ley/sareta_frame_ley.php','','frame_principal','N','N','N','Modulo frame de consulta de leyes de faros y boyas','','2008-07-04 22:40:36',NULL);
INSERT INTO `modulo` VALUES (159,30,-1,'N','0','sarimpley','sar_imp_ley','./recaudacion/mantenimiento/ley/sareta_impley.php','','frame_principal','N','N','N','','','2008-07-04 22:40:52',NULL);
INSERT INTO `modulo` VALUES (163,28,-1,'N','0','sarfrmagencianaviera','frm_list_agencianaiera','./recaudacion/mantenimiento/agencia_naviera/sareta_frame_agencianav.php','','frame_principal','N','N','N','Modulo frame de consulta de agencias navieras','','2008-07-04 22:41:21',NULL);
INSERT INTO `modulo` VALUES (165,21,-1,'N','0','sarprincipal','PRINCIPAL SARETA WEB','./public/sareta/sareta_principal.php','','_parent','Y','N','N','Modulo Principal del SARETA-WEB','','2008-07-04 20:11:52',NULL);
INSERT INTO `modulo` VALUES (166,22,337,'N','1','saraddpuerto','Registrar Puertos','./recaudacion/mantenimiento/puerto/sareta_addpuerto.php','','frame_principal','Y','N','N','','','2008-07-04 22:41:44',NULL);
INSERT INTO `modulo` VALUES (167,28,-1,'N','0','sarfrmdelegacion','frm_list_delegacion','./mantenimiento_general/mantenimiento/delegacion/sareta_frame_delegacion.php','','frame_principal','N','N','N','Modulo frame de consulta de delegaciones','','2008-07-07 10:19:24',NULL);
INSERT INTO `modulo` VALUES (168,28,338,'N','1','sarconsdelegacion','Consultar Delegaciones','./administracion_general/mantenimiento/delegacion/sareta_consdelegacion.php','','frame_principal','Y','N','N','Modulo de consulta de delegaciones registradas','','2008-07-07 09:34:52',NULL);
INSERT INTO `modulo` VALUES (169,28,337,'N','1','sarconspuerto','Consultar  Puertos','./recaudacion/mantenimiento/puerto/sareta_conspuerto.php','','frame_principal','Y','N','N','Modulo de Consulta de Puertos Registrados en SARETA','','2008-07-04 22:42:25',NULL);
INSERT INTO `modulo` VALUES (170,28,-1,'N','0','sarfrmpuerto','frm_list_puerto','./recaudacion/mantenimiento/puerto/sareta_frame_puerto.php','','frame_principal','N','N','N','Modulo frame de consulta de puertos','','2008-07-04 22:42:42',NULL);
INSERT INTO `modulo` VALUES (171,30,-1,'N','0','sarimppuerto','sar_imp_puerto','./recaudacion/mantenimiento/puerto/sareta_imppuerto.php','','frame_principal','N','N','N','','','2008-07-04 22:43:01',NULL);
INSERT INTO `modulo` VALUES (172,22,337,'N','1','saraddnumcontrol','Registrar Numero Control','./recaudacion/mantenimiento/numero_control/sareta_addnumcontrol.php','','frame_principal','Y','N','N','','','2008-07-04 22:43:18',NULL);
INSERT INTO `modulo` VALUES (173,28,337,'N','1','sarconsnumcontrol','Consultar Numero Control','./recaudacion/mantenimiento/numero_control/sareta_consnumcontrol.php','','frame_principal','Y','N','N','Modulo de consulta de numeros de control','','2008-07-04 22:43:36',NULL);
INSERT INTO `modulo` VALUES (174,28,-1,'N','0','sarfrmnumcontrol','frm_list_numcontrol','./recaudacion/mantenimiento/numero_control/sareta_frame_numcontrol.php','','frame_principal','N','N','N','Modulo frame de consulta de numeros de control','','2008-07-04 22:44:47',NULL);
INSERT INTO `modulo` VALUES (175,22,337,'N','1','saraddmonedacambio','Registrar Cambio Moneda','./recaudacion/mantenimiento/moneda_cambio/sareta_addmonedacambio.php','','frame_principal','Y','N','N','','','2008-07-09 10:54:20',NULL);
INSERT INTO `modulo` VALUES (178,28,64,'N','1','sarfrmmonedacambio','frm_list_monedacambio','./recaudacion/mantenimiento/moneda_cambio/sareta_frame_cambiomoneda.php','','frame_principal','N','N','N','Modulo frame de consulta de cambios de moneda','','2008-07-04 22:44:35',NULL);
INSERT INTO `modulo` VALUES (179,28,337,'N','1','sarconsmonedacambio','Consultar Cambio Moneda.','./recaudacion/mantenimiento/moneda_cambio/sareta_consmonedacambio.php','','frame_principal','Y','N','N','Modulo de consulta de cambios de moneda','','2008-07-09 11:05:34',NULL);
INSERT INTO `modulo` VALUES (180,30,64,'N','1','sarimpdelegacion','sar_imp_delegacion','./recaudacion/mantenimiento/delegacion/sareta_impdelegaciones.php','','frame_principal','N','N','N','','','2008-07-04 22:45:27',NULL);
INSERT INTO `modulo` VALUES (181,22,339,'N','1','saraddbancocuenta','Registrar Cuenta Banco','./contabilidad/mantenimiento/banco_cuenta/sareta_addbancocuenta.php','','frame_principal','Y','N','N','','','2008-07-07 11:20:15',NULL);
INSERT INTO `modulo` VALUES (184,30,64,'N','1','sarimpnumcontrol','sar_imp_numcontrol','./recaudacion/mantenimiento/numero_control/sareta_impnumcontrol.php','','frame_principal','N','N','N','','','2008-07-04 22:46:29',NULL);
INSERT INTO `modulo` VALUES (185,28,62,'N','1','sarfrmbancocuenta','frm_list_bancocuenta','./contabilidad/mantenimiento/banco_cuenta/sareta_frame_cuentabancos.php','','frame_principal','N','N','N','Modulo frame de consulta de cuentas de bancos','','2008-07-04 22:47:01',NULL);
INSERT INTO `modulo` VALUES (186,28,339,'N','1','sarconsbancocuenta','Consultar Ctas de Bancos','./contabilidad/mantenimiento/banco_cuenta/sareta_consbancocuenta.php','','frame_principal','Y','N','N','Modulo de consulta de cuentas de bancos','','2008-07-07 11:31:39',NULL);
INSERT INTO `modulo` VALUES (187,22,337,'N','1','saraddinteresbancario','Registrar Int. Bancario','./recaudacion/mantenimiento/interes_bancario/sareta_addinteresbancarios.php','','frame_principal','Y','N','N','','','2008-07-04 22:48:00',NULL);
INSERT INTO `modulo` VALUES (188,28,337,'N','1','sarconsinteresbancario','Consultar Int. Bancarios','./recaudacion/mantenimiento/interes_bancario/sareta_consinteresbancario.php','','frame_principal','Y','N','N','Modulo de consulta de intereses bancarios','','2008-07-04 22:48:30',NULL);
INSERT INTO `modulo` VALUES (189,28,64,'N','1','sarfrminteresbancario','frm_list_interesbancario','./recaudacion/mantenimiento/interes_bancario/sareta_frame_interesbancario.php','','frame_principal','N','N','N','Modulo frame de consulta de intereses bancarios','','2008-07-04 22:49:04',NULL);
INSERT INTO `modulo` VALUES (190,27,337,'N','1','saraddavisorecalada','Aviso de Recalada','./recaudacion/transacciones/mov_aviso_recalada/sareta_addavisorecalada.php','','frame_principal','Y','N','N','','','2008-07-04 22:49:44',NULL);
INSERT INTO `modulo` VALUES (191,30,64,'N','1','sarimpinteresbancario','sar_imp_interesbancario','./recaudacion/mantenimiento/interes_bancario/sareta_impinteresbancario.php','','frame_principal','N','N','N','','','2008-07-04 22:50:17',NULL);
INSERT INTO `modulo` VALUES (194,30,64,'N','1','sarimpmonedacambio','sar_imp_monedacambio','./recaudacion/mantenimiento/moneda_cambio/sareta_impcambiomoneda.php','','frame_principal','N','N','N','','','2008-07-04 22:50:39',NULL);
INSERT INTO `modulo` VALUES (198,22,337,'N','1','saradddistanciapuerto','Registrar Distancia Pto.','./recaudacion/mantenimiento/distancia_puerto/sareta_adddistanciapuerto.php','','frame_principal','Y','N','N','','','2008-07-04 22:51:02',NULL);
INSERT INTO `modulo` VALUES (199,31,-1,'N','0',NULL,'pop_grid','pop_grid.php','','frame_principal','N','N','N','','','2006-05-23 14:21:10',NULL);
INSERT INTO `modulo` VALUES (200,31,-1,'N','0',NULL,'grid','grid.php','','frame_principal','N','N','N','','','2006-05-23 14:22:22',NULL);
INSERT INTO `modulo` VALUES (201,28,-1,'N','0','sarfrmdistanciapuerto','sareta_frm_distanciapuerto','sareta_frame_distanciapuerto.php','','frame_principal','N','N','N','Modulo frame de consulta de distancias de puertos','','2008-07-07 09:52:55',NULL);
INSERT INTO `modulo` VALUES (202,28,337,'N','1','sarconsdistanciapuerto','Consultar Distancia Pto.','./recaudacion/mantenimiento/distancia_puerto/sareta_consdistanciapuerto.php','','frame_principal','Y','N','N','Modulo de consulta de distancia de puerto','','2008-07-07 09:31:16',NULL);
INSERT INTO `modulo` VALUES (203,30,64,'N','1','sarimpdstanciapuerto','sareta_imp_distanciapuerto','sareta_impdistanciapuerto.php','','frame_principal','N','N','N','','','2008-07-07 09:52:04',NULL);
INSERT INTO `modulo` VALUES (204,30,-1,'N','0','sarimpbuque','sareta_imp_buque','sareta_impbuque.php','','frame_principal','N','N','N','','','2008-07-07 09:51:54',NULL);
INSERT INTO `modulo` VALUES (205,46,337,'N','1','frameavisorecalada','frm_list_avisorecalada','./public/mov_aviso_recalada/sareta_frame_aviso_recalada.php','','frame_principal','N','N','N','','','2008-07-07 09:27:27',NULL);
INSERT INTO `modulo` VALUES (206,46,337,'N','1','consavisorecalada','Avisos Recalada','./recaudacion/transacciones/mov_aviso_recalada/sareta_cons_aviso_recalada.php','','frame_principal','Y','N','N','Modulo de consulta de avisos de recaladas cancelados','','2008-07-08 12:37:13',NULL);
INSERT INTO `modulo` VALUES (207,30,-1,'N','0','sarimpagencianaviera','sareta_imp_agencianaviera','sareta_impagencianaviera.php','','frame_principal','N','N','N','','','2008-07-07 09:51:44',NULL);
INSERT INTO `modulo` VALUES (208,27,337,'N','1','saraddpago','Cargar Pagos','./recaudacion/transacciones/pago/sareta_addpagos.php','','frame_principal','Y','N','N','','','2008-07-04 22:52:58',NULL);
INSERT INTO `modulo` VALUES (209,31,-1,'N','0',NULL,'frame_grid_rows','frame_grid_rows.php','','frame_principal','N','N','N','','','2006-05-23 14:21:37',NULL);
INSERT INTO `modulo` VALUES (214,30,-1,'N','0','sarimpbanco','sar_imp_banco','./contabilidad/mantenimiento/banco/sareta_impbanco.php','','frame_principal','N','N','N','','','2008-07-04 22:51:56',NULL);
INSERT INTO `modulo` VALUES (215,30,-1,'N','0','sarimpbancocuenta','sareta_imp_bancocuenta','sareta_impbancocuenta.php','','frame_principal','N','N','N','','','2008-07-07 09:53:24',NULL);
INSERT INTO `modulo` VALUES (216,27,337,'N','1','sarfrmdetallepago','sareta_frame_detalle_pago','./recaudacion/transacciones/pago/sareta_frame_detalle_pago.php','','frame_principal','N','N','N','','','2008-07-04 22:52:51',NULL);
INSERT INTO `modulo` VALUES (217,6,-1,'N','0',NULL,'int_frm_wallapapers','intranet_frame_wallpapers.php','','frame_principal','N','N','N','listado de wallpapers','','2008-07-11 11:46:12',NULL);
INSERT INTO `modulo` VALUES (218,1,-1,'N','0','intconsdivision','Listado Divisiones','./public/intranet/gestion_usuario/division/intranet_consdivisiones.php','','frame_principal','Y','N','N','Modulo de consulta de divisiones registradas','','2008-08-19 10:03:34',NULL);
INSERT INTO `modulo` VALUES (219,8,-1,'N','0',NULL,'Frame Música','intranet_frame_musica.php','','frame_principal','N','N','N','Modulo de visualizacion del listado de musica registrada','','2006-06-29 23:35:08',NULL);
INSERT INTO `modulo` VALUES (239,1,-1,'N','0',NULL,'','intranet_frame_tipousuario.php','','frame_principal','N','N','N','Modulo de visualizacion del listado de tipos de usuarios registrados','osalazar','2008-07-07 09:52:47',NULL);
INSERT INTO `modulo` VALUES (240,1,-1,'N','0','intconstipousuario','Listado Tipos de Usuarios','./public/intranet/gestion_usuario/usuarios/intranet_constipousuario.php','','frame_principal','Y','N','N','Modulo de consulta de tipos de usuarios registrados','osalazar','2008-08-26 09:38:49',NULL);
INSERT INTO `modulo` VALUES (241,1,-1,'N','0','intaddcargo','Registrar Cargo','./public/intranet/gestion_usuario/cargo/intranet_addcargo.php','','frame_principal','Y','N','N','Modulo para el registro de cargo','osalazar','2008-08-18 13:57:37',NULL);
INSERT INTO `modulo` VALUES (242,1,-1,'N','0','intconscargo','Listado Cargos','./public/intranet/gestion_usuario/cargo/intranet_conscargos.php','','frame_principal','Y','N','N','Modulo de consulta de cargos registrados','osalazar','2008-08-18 13:56:52',NULL);
INSERT INTO `modulo` VALUES (243,1,-1,'N','0','intfrmcargo','frm_list_cargo','intranet_frame_cargos.php','','frame_principal','N','N','N','Modulo de visualizacion del listado de los cargos registrados','osalazar','2008-07-07 09:55:03',NULL);
INSERT INTO `modulo` VALUES (244,40,-1,'N','0','intaddexttelefonica','Registrar Ext. Telefonica','./public/intranet/servicio/telefonia/intranet_addexttelefonica.php','','frame_principal','Y','N','N','','osalazar','2008-09-03 10:41:48',NULL);
INSERT INTO `modulo` VALUES (245,40,-1,'N','0','intconsexttelefonica','Listín Extensiones Telefónicas','./public/intranet/servicio/telefonia/intranet_consexttelefonicas.php','','frame_principal','Y','N','N','','osalazar','2008-11-04 16:02:19',NULL);
INSERT INTO `modulo` VALUES (246,40,-1,'N','0',NULL,'int_frm_exttelefonic','intranet_frame_exttelefonicas.php','','frame_principal','N','N','N','','osalazar','2008-07-11 11:46:02',NULL);
INSERT INTO `modulo` VALUES (247,1,-1,'N','0','intaddcompaniaparametro','Compañia Parametros','./public/intranet/administracion_sistema/compania/intranet_addcompaniaparametro.php','','frame_principal','Y','N','N','Modulo para la actualización de los parametros generales de las compañias registradas','osalazar','2008-08-15 14:35:03',NULL);
INSERT INTO `modulo` VALUES (248,1,-1,'N','0',NULL,'Frame Usuarios','intranet_frame_usuarios.php','','frame_principal','N','N','N','Modulo de visalizacion de listado de usuarios registrados','osalazar','2006-06-29 23:30:23',NULL);
INSERT INTO `modulo` VALUES (249,1,-1,'N','0',NULL,'Frame Divisiones','intranet_frame_divisiones.php','','frame_principal','N','N','N','Modulo de visualizacion del listado de las divisiones registradas','osalazar','2006-06-29 23:27:34',NULL);
INSERT INTO `modulo` VALUES (250,1,-1,'N','0',NULL,'Frame perfiles','intranet_frame_perfiles.php','','frame_principal','N','N','N','Modulo de visualizacion del listado de perfiles registrados','osalazar','2006-06-29 23:29:00',NULL);
INSERT INTO `modulo` VALUES (251,29,-1,'N','0',NULL,'Frame Asignacion Grupos','intranet_frame_asignaciongrupos.php','','frame_principal','N','N','N','Modulo para asignacion de grupos a un perfil','osalazar','2006-08-10 15:12:44',NULL);
INSERT INTO `modulo` VALUES (252,29,-1,'N','0',NULL,'Frame Asignación Modulos','intranet_frame_asignacionmodulos.php','','frame_principal','N','N','N','Modulo para la asignación de modulos a un perfil','osalazar','2006-08-10 15:13:26',NULL);
INSERT INTO `modulo` VALUES (253,29,-1,'N','0',NULL,'Frame Modulos','intranet_frame_modulos.php','','frame_principal','N','N','N','Modulo frame de visualización  de modulos registrados','OSALAZAR','2006-08-10 15:14:15',NULL);
INSERT INTO `modulo` VALUES (254,32,-1,'N','0',NULL,'int_frm_expedientes','intranet_frame_expedientes.php','','frame_principal','N','N','N','','OSALAZAR','2008-07-11 11:45:56',NULL);
INSERT INTO `modulo` VALUES (255,32,-1,'N','0','intconsexpediente','Listado Expedientes','./public/intranet/gestion_usuario/usuarios/expediente/intranet_consexpedientes.php','','frame_principal','Y','N','N','','OSALAZAR','2008-10-28 12:16:15',NULL);
INSERT INTO `modulo` VALUES (256,32,-1,'N','0','intaddexpediente','Registrar Expediente Personal','./public/intranet/gestion_usuario/usuarios/expediente/intranet_addexpediente.php','','frame_principal','N','N','N','','OSALAZAR','2008-10-28 12:14:30',NULL);
INSERT INTO `modulo` VALUES (257,32,-1,'N','0','intadddatoscomplementarios','Registrar Datos Comple.','./public/intranet/gestion_usuario/usuarios/intranet_adddatoscomplementarios.php','','frame_principal','N','N','N','','OSALAZAR','2008-09-04 16:28:17',NULL);
INSERT INTO `modulo` VALUES (258,32,-1,'N','0','nitaddhijo','Registrar Hijos','./public/intranet/gestion_usuario/usuarios/intranet_addhijo.php','','frame_principal','N','N','N','','OSALAZAR','2008-09-04 16:27:31',NULL);
INSERT INTO `modulo` VALUES (259,32,-1,'N','0','intaddeducacion','Registrar Educación','./public/intranet/administracion_sistema/usuarios/intranet_addeducacion.php','','frame_principal','N','N','N','','OSALAZAR','2008-08-19 10:58:27',NULL);
INSERT INTO `modulo` VALUES (260,33,-1,'N','0','intconsmanuales','Normas y Procedimientos','intranet_consmanuales.php','','frame_principal','Y','N','N','Recopilación de archivos en formato PDF de los manuales de normas y procedimientos','OSALAZAR','2008-08-19 08:58:21',NULL);
INSERT INTO `modulo` VALUES (261,32,-1,'N','0','intaddidioma','Registrar Idiomas','./public/intranet/gestion_usuario/usuarios/intranet_addidiomas.php','','frame_principal','N','N','N','','OSALAZAR','2008-09-04 16:28:10',NULL);
INSERT INTO `modulo` VALUES (262,32,-1,'N','0','intaddexperiencia','Registrar Experiencia Pro','./public/intranet/gestion_usuario/usuarios/intranet_addexperiencia.php','','frame_principal','N','N','N','','OSALAZAR','2008-09-04 16:28:12',NULL);
INSERT INTO `modulo` VALUES (263,29,-1,'N','0','intaddtema','Registrar Temas','intranet_addtema.php','','frame_principal','Y','N','N','Modulo de registro de temas','OSALAZAR','2008-08-19 08:54:27',NULL);
INSERT INTO `modulo` VALUES (264,29,-1,'N','0','intconstema','Listado de Temas','intranet_constemas.php','','frame_principal','Y','N','N','Modulo de consulta de temas registrados','OSALAZAR','2008-08-19 08:54:35',NULL);
INSERT INTO `modulo` VALUES (265,29,-1,'N','0',NULL,'Frame Temas','intranet_frame_temas.php','','frame_principal','N','N','N','Modulo frane de visualización de temas','OSALAZAR','2006-08-10 15:14:42',NULL);
INSERT INTO `modulo` VALUES (266,34,-1,'N','0','intconsvideo','Videos Institucionales','./public/intranet/servicio/video/intranet_consvideos.php','','frame_principal','Y','N','N','Grupo de recopilación de videos institucionales','OSALAZAR','2008-09-03 12:23:57',NULL);
INSERT INTO `modulo` VALUES (267,32,-1,'N','0','intimpexpediente','int_imp_expediente','intranet_impexpediente.php','','frame_principal','N','N','N','','OSALAZAR','2008-08-19 08:54:57',NULL);
INSERT INTO `modulo` VALUES (268,20,-1,'N','0',NULL,'Frame Peticiones Pendient','intranet_frame_peticionespendientes.php','','frame_principal','N','N','N','','OSALAZAR','2006-06-08 13:59:58',NULL);
INSERT INTO `modulo` VALUES (269,20,-1,'N','0','intaddsolucionpeticion','Registrar Solucion','intranet_addpeticionsolucion.php','','frame_principal','N','N','N','','OSALAZAR','2008-08-19 08:55:16',NULL);
INSERT INTO `modulo` VALUES (270,36,-1,'N','0','intaddnoticia','Registrar Noticia','./public/intranet/servicio/noticia/intranet_addnoticia.php','','frame_principal','Y','N','N','Modulo de registro de noticias','osalazar','2008-08-15 11:13:53',NULL);
INSERT INTO `modulo` VALUES (271,36,-1,'N','0','intconsnoticia','Listado de Noticias','./public/intranet/servicio/noticia/intranet_consnoticias.php','','frame_principal','Y','N','N','Modulo de consulta de noticias registradas','osalazar','2008-08-15 11:45:16',NULL);
INSERT INTO `modulo` VALUES (272,36,-1,'N','0','intfrmnoticia','Frame Noticias','intranet_frame_noticias.php','','frame_principal','N','N','N','Modulo de registro de noticias','osalazar','2008-08-15 11:17:10',NULL);
INSERT INTO `modulo` VALUES (273,31,-1,'N','0',NULL,'Visor de Noticias','intranet_visornoticias.php','','frame_principal','N','N','N','','osalazar','2006-06-12 10:35:16',NULL);
INSERT INTO `modulo` VALUES (274,39,-1,'N','0','intaddnuevopass','Actualizar Contraseña','./public/intranet/gestion_usuario/usuarios/intranet_addnuevopass.php','','frame_principal','Y','N','N','','osalazar','2008-09-03 16:22:38',NULL);
INSERT INTO `modulo` VALUES (275,39,-1,'N','0','intconsexpedientepersonal','Expediente Personal','./public/intranet/gestion_usuario/usuarios/expediente/intranet_consexpediente.php','','frame_principal','Y','N','N','','msalcedo','2008-11-04 12:48:51',NULL);
INSERT INTO `modulo` VALUES (276,40,-1,'N','0',NULL,'Pdf Listado Telefónico','intranet_implistintelefonico.php','','frame_principal','N','N','N','','osalazar','2006-06-15 16:14:01',NULL);
INSERT INTO `modulo` VALUES (277,40,-1,'N','0','intconslistadotel','Listado Telefonico','./public/intranet/servicio/telefonia/intranet_conslistadotelefonico.php','','frame_principal','Y','N','N','','osalazar','2008-09-03 10:47:23',NULL);
INSERT INTO `modulo` VALUES (278,39,-1,'N','0','intconsusuarioext','Buscar Extencion Tel.','./public/intranet/servicio/telefonia/intranet_consusuarioextencion.php','','frame_principal','Y','N','N','','osalazar','2008-08-27 09:31:36',NULL);
INSERT INTO `modulo` VALUES (279,39,-1,'N','0',NULL,'Frame Usuarios Extencion','intranet_frame_usuarioextencion.php','','frame_principal','N','N','N','','osalazar','2006-06-19 10:15:08',NULL);
INSERT INTO `modulo` VALUES (280,33,-1,'N','0','intconsmanualtel','Servicio Telefónico','./public/intranet/servicio/telefonia/intranet_consmanualtelefonico.php','','frame_principal','Y','N','N','','osalazar','2008-09-04 14:58:55',NULL);
INSERT INTO `modulo` VALUES (281,1,-1,'N','0','intconsusuarioavanz','Listado Usuarios Avanz.','intranet_consusuariosavanzado.php','','frame_principal','Y','N','N','Modulo de consulta avanzada de usuarios registrados','osalazar','2008-08-19 08:57:39',NULL);
INSERT INTO `modulo` VALUES (282,1,-1,'N','0',NULL,'Impresión Usuarios Avanz.','intranet_impusuariosavanzado.php','','frame_principal','N','N','N','Modulo de impresion avanzada de usuarios','osalazar','2006-06-29 23:26:43',NULL);
INSERT INTO `modulo` VALUES (283,1,-1,'N','0','intsesactivas','Lista Sessiones Activas','./public/intranet/gestion_usuario/perfiles/intranet_conssessionesactivas.php','','frame_principal','Y','N','N','Modulo de Administración de Sessiones Activas','msalcedo','2008-08-15 14:42:52',NULL);
INSERT INTO `modulo` VALUES (284,1,-1,'N','0',NULL,'Frame Sessiones Activas','intranet_frame_sessionesactivas.php','','frame_principal','N','N','N','MOdulo Frame de consulta Sessiones Activas','msalcedo','2006-08-10 15:19:08',NULL);
INSERT INTO `modulo` VALUES (285,1,-1,'N','0','intcopiarperfil','Copiar Perfil','./public/intranet/gestion_usuario/perfiles/intranet_copiarperfil.php','','frame_principal','Y','N','N','Modulo para copiar los registros de acceso de un perfil a otro','osalazar','2008-08-15 14:41:07',NULL);
INSERT INTO `modulo` VALUES (286,6,-1,'N','0','intconswallpaperpub','Fondos Presentaciones','./public/intranet/servicio/wallpaper/intranet_conswallpaperspublico.php','','frame_principal','Y','N','N','','osalazar','2008-09-05 11:18:57',NULL);
INSERT INTO `modulo` VALUES (287,6,-1,'N','0',NULL,'Frame Fondos Present.','intranet_frame_wallpaperspublico.php','','frame_principal','N','N','N','','osalazar','2006-07-03 00:52:26',NULL);
INSERT INTO `modulo` VALUES (288,6,-1,'N','0','intconslogos','Logos e Imágenes','./public/intranet/servicio/logo/intranet_conslogos.php','','frame_principal','Y','N','N','','osalazar','2008-09-04 16:27:57',NULL);
INSERT INTO `modulo` VALUES (289,33,-1,'N','0','intconstutorial','Tutoriales y Cursos','./public/intranet/servicio/tutoria/intranet_constutoriales.php','','frame_principal','Y','N','N','Recopilación de Manuales y Formatos.','osalazar','2008-09-04 14:05:30',NULL);
INSERT INTO `modulo` VALUES (292,29,-1,'N','0','intfrmgrupo','Frame grupo','intranet_frame_grupos.php','','frame_principal','N','N','N','Modulo frame de consulta de grupos','osalazar','2008-08-14 10:57:07',NULL);
INSERT INTO `modulo` VALUES (293,1,-1,'N','0',NULL,'Frame Compañias','intranet_frame_companias.php','','frame_principal','N','N','N','Modulo frame de consulta de compañias','osalazar','2006-08-10 16:20:06',NULL);
INSERT INTO `modulo` VALUES (294,27,337,'N','1','sarcalmora','Cálculo de Mora','./recaudacion/transacciones/calculo_mora/sareta_calculo_mora.php','','frame_principal','Y','N','N','Modulo Sareta para el Cálculo de la Mora','osalazar','2008-07-15 11:18:26',NULL);
INSERT INTO `modulo` VALUES (295,30,64,'N','1','sarimpcalmora','sar_imp_mora','./recaudacion/transacciones/calculo_mora/sareta_impmora.php','','frame_principal','Y','N','N','Modulo de Impresión de Mora','osalazar','2008-07-17 10:21:40',NULL);
INSERT INTO `modulo` VALUES (296,39,-1,'N','0','intconscumpleaño','Cumpleañeros del Mes','./public/intranet/servicio/cumpleaneros/intranet_conscumpleanos.php','','frame_principal','Y','N','N','Modulo de consulta de cumpleañeros del mes','osalazar','2008-09-22 11:25:42',NULL);
INSERT INTO `modulo` VALUES (297,39,-1,'N','0',NULL,'int_imp_cumpleanos','intranet_impcumpleanos.php','','frame_principal','N','N','N','Modulo de impresion de cumpleañeros del mes','osalazar','2008-07-11 11:45:34',NULL);
INSERT INTO `modulo` VALUES (298,43,-1,'N','0','intaddcomunicacion','Registrar Comunicación','intranet_addcomunicacion.php','','frame_principal','Y','N','N','Modulo para el registro de comunicaciones','osalazar','2008-08-19 08:56:42',NULL);
INSERT INTO `modulo` VALUES (299,43,-1,'N','0','intconscomunicacion','Listado Comunicaciones','intranet_conscomunicacion.php','','frame_principal','Y','N','N','Modulo de consulta de comunicaciones registradas','osalazar','2008-08-19 08:56:32',NULL);
INSERT INTO `modulo` VALUES (300,43,-1,'N','0',NULL,'Frame Comunicaciones','intranet_frame_comunicacion.php','','frame_principal','N','N','N','Modulo frame de comunicaciones registradas','osalazar','2006-09-21 10:39:43',NULL);
INSERT INTO `modulo` VALUES (301,43,-1,'N','0','intconscomavanz','Comunicaciones Avanz.','intranet_conscomunicacionavanzado.php','','frame_principal','Y','N','N','Modulo de Consulta Avanzada de Comunicaciones Registradas','osalazar','2008-08-19 08:56:20',NULL);
INSERT INTO `modulo` VALUES (303,46,337,'N','1','consavisoanual','Avisos Anuales','./recaudacion/transacciones/mov_aviso_anual/sareta_cons_aviso_anual.php','','frame_principal','Y','N','N','Modulo de consulta de los registros de recalada anuales registrados','osalazar','2008-07-10 14:49:36',NULL);
INSERT INTO `modulo` VALUES (304,46,337,'N','1','frameavisoanual','frm_list_avisoanual','./public/mov_aviso_anual/sareta_frame_aviso_anual.php','','frame_principal','N','N','N','Modulo Frame de los registros de recalada anuales registrados','osalazar','2008-07-07 09:27:13',NULL);
INSERT INTO `modulo` VALUES (305,27,337,'N','1','sarimppago','sar_imp_pago','./recaudacion/transacciones/pago/sareta_imppago.php','','frame_principal','N','N','N','Modulo de Impresion de Pagos Generados y Cerrados','osalazar','2008-07-04 22:54:01',NULL);
INSERT INTO `modulo` VALUES (306,39,-1,'N','0','intaddactividaddiaria','Registrar Act. Diaria','intranet_addactividaddiaria.php','','frame_principal','N','N','N','Modulo para registrar actividad diaria de los usuarios','osalazar','2008-08-19 08:56:06',NULL);
INSERT INTO `modulo` VALUES (307,33,-1,'N','0','intconsge','Gobierno Electronico','./public/intranet/servicio/gobierno/intranet_consgobiernoelectronico.php','','frame_principal','Y','N','N','Consulta de los archivos de Gobierno Electronico','osalazar','2008-09-04 12:34:29',NULL);
INSERT INTO `modulo` VALUES (308,39,-1,'N','0','intconslistadomadre','Listado de Madres','intranet_conslistadomadres.php','','frame_principal','Y','N','N','','osalazar','2008-08-19 08:55:45',NULL);
INSERT INTO `modulo` VALUES (309,39,-1,'N','0',NULL,'Frame Listado Madres','intranet_frame_listadomadres.php','','frame_principal','N','N','N','','osalazar','2007-01-25 10:15:01',NULL);
INSERT INTO `modulo` VALUES (311,39,-1,'N','0','intconsfalta','Faltas y Comisiones','pediente/','','frame_principal','N','N','N','Modulo de consulta de las faltas, reposos, comisiones, vacaciones, entre otras generadas por el sistema de control de acceso.','osalazar','2008-11-04 12:47:59',NULL);
INSERT INTO `modulo` VALUES (312,39,-1,'N','0',NULL,'Frame Faltas','intranet_frame_faltas.php','','frame_principal','N','N','N','Frame de consulta de las fatas registradas de los usuarios','osalazar','2007-04-16 10:32:08',NULL);
INSERT INTO `modulo` VALUES (313,39,-1,'N','0','intconswindsx','Consultar WinDsx','intranet_conswindsx.php','','frame_principal','N','N','N','','osalazar','2008-09-22 11:21:28',NULL);
INSERT INTO `modulo` VALUES (314,39,-1,'N','0',NULL,'Frame Windsx','intranet_frame_windsx.php','','frame_principal','N','N','N','','osalazar','2007-04-25 14:03:07',NULL);
INSERT INTO `modulo` VALUES (315,27,337,'N','1','saraddpcp','Liquidacion Complementaria','./recaudacion/transacciones/pago_complementario_posterior/sareta_addliquidacioncomplementaria.php','','frame_principal','Y','N','N','','osalazar','2008-07-15 14:20:33',NULL);
INSERT INTO `modulo` VALUES (317,27,337,'N','1','sarconsreversarpago','Reversar Pago','./recaudacion/transacciones/reversar_pago/sareta_consreversarpago.php','','frame_principal','Y','N','N','','osalazar','2008-07-15 16:01:19',NULL);
INSERT INTO `modulo` VALUES (318,22,337,'N','1','saraddarmador','Registrar Armador','./recaudacion/mantenimiento/armador/sareta_addarmador.php','','frame_principal','Y','N','N','','osalazar','2008-07-08 11:54:49',NULL);
INSERT INTO `modulo` VALUES (319,28,337,'N','1','sarconsarmador','Consultar Armadores','./recaudacion/mantenimiento/armador/sareta_consarmador.php','','frame_principal','Y','N','N','','osalazar','2008-07-07 09:31:24',NULL);
INSERT INTO `modulo` VALUES (320,28,64,'N','1','sarfrmarmador','frm_list_armador','./recaudacion/mantenimiento/armador/sareta_frame_armador.php','','frame_principal','N','N','N','','osalazar','2008-07-07 09:53:42',NULL);
INSERT INTO `modulo` VALUES (323,46,337,'N','1','impavisorecalada','Imp. Avisos Recalada','./public/mov_aviso_recalada/sareta_imp_aviso_recalada.php','','frame_principal','N','N','N','','osalazar','2008-05-06 15:43:29',NULL);
INSERT INTO `modulo` VALUES (324,1,-1,'N','0','intaddclave','cambiar_clave','intranet_addclave.php','','frame_principal','N','Y','N','','osalazar','2008-08-19 09:50:21',NULL);
INSERT INTO `modulo` VALUES (325,39,-1,'N','0',NULL,'int_imp_windsx','intranet_impwindsx.php','','frame_principal','N','Y','N','','osalazar','2008-07-11 11:45:51',NULL);
INSERT INTO `modulo` VALUES (327,48,-1,'N','0','intaddvisitante','Registrar Visitante','intranet_addvisitante.php','','frame_principal','Y','N','N','','osalazar','2008-08-19 09:06:28',NULL);
INSERT INTO `modulo` VALUES (328,48,-1,'N','0','intconsvisitante','Consultar Visitantes','intranet_consvisitante.php','','frame_principal','Y','N','N','','osalazar','2008-08-19 08:57:29',NULL);
INSERT INTO `modulo` VALUES (329,48,-1,'N','0',NULL,'Frame Visitante','intranet_frame_visitante.php','','frame_principal','N','N','N','','osalazar','2008-01-21 12:04:12',NULL);
INSERT INTO `modulo` VALUES (330,48,-1,'N','0','intaddvisempresa','Registrar Empresa','intranet_addvisitanteempresa.php','','frame_principal','Y','N','N','','osalazar','2008-08-19 09:06:21',NULL);
INSERT INTO `modulo` VALUES (331,48,-1,'N','0',NULL,'Frame Visitante Empresa','intranet_frame_visitanteempresa.php','','frame_principal','N','N','N','','osalazar','2008-01-21 14:14:49',NULL);
INSERT INTO `modulo` VALUES (332,48,-1,'N','0','intconsvisempresa','Consultar Empresas','intranet_consvisitanteempresa.php','','frame_principal','Y','N','N','','osalazar','2008-08-19 08:57:23',NULL);
INSERT INTO `modulo` VALUES (333,48,-1,'N','0','intaddvistarjeta','Registrar Tarjeta','intranet_addvisitantetarjeta.php','','frame_principal','Y','N','N','','osalazar','2008-08-19 09:06:12',NULL);
INSERT INTO `modulo` VALUES (334,48,-1,'N','0','intconsvistarjeta','Consultar Tarjeta','intranet_consvisitantetarjeta.php','','frame_principal','Y','N','N','','osalazar','2008-08-19 08:57:16',NULL);
INSERT INTO `modulo` VALUES (335,48,-1,'N','0',NULL,'Frame Tarjeta','intranet_frame_visitantetarjeta.php','','frame_principal','N','N','N','','osalazar','2008-01-21 15:01:25',NULL);
INSERT INTO `modulo` VALUES (336,48,-1,'N','0','intaddasigntarjeta','Asignar Tarjeta','intranet_addasignartarjeta.php','','frame_principal','N','N','N','','osalazar','2008-08-19 09:50:30',NULL);
INSERT INTO `modulo` VALUES (337,21,-1,'Y','0',NULL,'Recaudación de la Tasa','sareta_principal.php','','','N','N','N','','osalazar','2008-01-29 09:00:39',NULL);
INSERT INTO `modulo` VALUES (338,21,-1,'Y','0',NULL,'Administracion General','sareta_principal.php','','','N','N','N','','osalazar','2008-01-29 14:33:53',NULL);
INSERT INTO `modulo` VALUES (339,21,-1,'Y','0',NULL,'Contabilidad','sareta_principal.php','','','N','N','N','','osalazar','2008-02-01 08:27:21',NULL);
INSERT INTO `modulo` VALUES (340,21,-1,'Y','0',NULL,'Gerencial','sareta_principal.php','','','N','N','N','','osalazar','2008-02-01 08:27:57',NULL);
INSERT INTO `modulo` VALUES (344,46,337,'N','1','framemovcompensacion','Frame Notas de Credito','./recaudacion/transacciones/mov_compensacion/sareta_frame_movcompensacion.php','','','N','N','N','','osalazar','2008-07-16 14:47:33',NULL);
INSERT INTO `modulo` VALUES (345,46,337,'N','1','consmovcompensacion','Notas de Credito','./recaudacion/transacciones/mov_compensacion/sareta_consmovcompensacion.php','','sareta_principal','Y','N','N','','osalazar','2008-07-16 14:47:27',NULL);
INSERT INTO `modulo` VALUES (346,46,337,'N','1','sarconspcp','Complementario Posterior','./recaudacion/transacciones/pago_complementario_posterior/sareta_conspcp.php','','','Y','N','N','','osalazar','2008-07-17 09:12:58',NULL);
INSERT INTO `modulo` VALUES (347,46,337,'N','1','sarfrmpcp','frm_list_pcp','./recaudacion/transacciones/pago_complementario_posterior/sareta_frame_pcp.php','','','N','N','N','','osalazar','2008-07-17 09:13:08',NULL);
INSERT INTO `modulo` VALUES (348,46,337,'N','1','sarconspci','Complementario Inmediato','./recaudacion/transacciones/pago_complementario_inmediato/sareta_conspci.php','','sareta_principal','Y','N','N','','osalazar','2008-07-17 08:56:57',NULL);
INSERT INTO `modulo` VALUES (349,46,337,'N','1','sarfrmpci','frm_list_pci','./public/pago_complementario_inmediato/sareta_frame_pci.php','','','N','N','N','','osalazar','2008-07-17 08:57:03',NULL);
INSERT INTO `modulo` VALUES (350,22,338,'N','1','importsareta','Importacion SARETA','./administracion_general/mantenimiento/importacion_odbc/index.php','','','Y','N','N','','osalazar','2008-07-07 10:20:18',NULL);
INSERT INTO `modulo` VALUES (351,28,340,'N','1','histomov','Historico Movimientos','./gerencial/consulta/historico_movimiento/cons_historico_movimiento.php','','','Y','N','N','','osalazar','2008-07-04 23:28:24',NULL);
INSERT INTO `modulo` VALUES (353,46,337,'N','1','impavisoanual','Imp. Aviso Anual','./public/mov_aviso_anual/sareta_imp_aviso_anual.php','','','N','N','N','','osalazar','2008-05-22 08:49:12',NULL);
INSERT INTO `modulo` VALUES (354,49,-1,'N','0','addencwallpaper','Fondo de Pantalla Mensual','./public/intranet/encuesta/wallpapers/add_encuesta_wallpaper.php','','frame_principal','Y','N','N','Modulo para el registro de encuesta sobre el wallpaper mensual.','osalazar','2008-08-27 10:00:50',NULL);
INSERT INTO `modulo` VALUES (355,28,340,'N','1','frmhistomov','Frame Historico Movimient','./gerencial/consulta/sareta_frame_historico_movimiento.php','','','N','N','N','','osalazar','2008-07-04 23:28:11',NULL);
INSERT INTO `modulo` VALUES (356,46,337,'N','1','sarconsmovmora','Movimientos de Mora','./recaudacion/transacciones/mov_mora/sareta_cons_mov_mora.php','','','Y','N','N','','osalazar','2008-07-16 14:46:25',NULL);
INSERT INTO `modulo` VALUES (357,27,339,'N','1','addtraspconta','Traspaso de Fin de Dia','./contabilidad/transacciones/traspaso_contable/sc_add_traspaso_contable.php','','','Y','N','N','','osalazar','2008-07-04 23:28:03',NULL);
INSERT INTO `modulo` VALUES (358,50,337,'N','1','scimppcp','Pago Complementario','./recaudacion/transacciones/pago_complementario_posterior/sc_imp_pago_complementario.php','','','Y','N','N','','osalazar','2008-07-15 14:17:47',NULL);
INSERT INTO `modulo` VALUES (359,50,339,'N','1','impfindia','SC Inpresión Fin de Dia','./contabilidad/transacciones/traspaso_contable/imp_traspaso_contable_fin_dia.php','','','N','N','N','','osalazar','2008-07-04 23:27:44',NULL);
INSERT INTO `modulo` VALUES (360,27,337,'N','1','saraddavisoanual','Aviso Anual','./recaudacion/transacciones/mov_aviso_anual/sareta_addavisoanual.php','','frame_principal','Y','N','N','','osalazar','2008-07-04 23:30:03',NULL);
INSERT INTO `modulo` VALUES (361,27,337,'N','1','saraddmanavianual','Avisos Anuales','./recaudacion/transacciones/mov_aviso_anual/sareta_addmantavisoanual.php','','frame_principal','Y','N','N','Modulo de Mantenimiento de Avisos Anuales SARETA','osalazar','2008-07-04 23:56:54',NULL);
INSERT INTO `modulo` VALUES (369,53,-1,'N','0','intaddarticulo','Registrar Articulo','./public/intranet/control_material/intranet_addarticulo.php','','frame_principal','Y','N','N','','osalazar','2008-08-14 11:44:29',NULL);
INSERT INTO `modulo` VALUES (370,53,-1,'N','0','intconsarticulo','Consultar Articulos','./public/intranet/control_material/intranet_consarticulo.php','','frame_principal','Y','N','N','','osalazar','2008-08-14 17:47:14',NULL);
INSERT INTO `modulo` VALUES (371,53,-1,'N','0','intaddmantarticulo','Control Articulo','./public/intranet/control_material/intranet_addmantarticulo.php','','frame_principal','Y','N','N','','osalazar','2008-08-14 18:40:00',NULL);
INSERT INTO `modulo` VALUES (372,6,-1,'N','0','intaddwallpapersmes','Registrar Fondos Pantalla del Mes','./public/intranet/servicio/wallpaper/intranet_addwallpapesrmes.php','','frame_principal','Y','N','N','','osalazar','2008-08-28 09:21:47',NULL);
INSERT INTO `modulo` VALUES (373,49,-1,'N','0','intaddencuesta','Registrar Encuesta','./public/intranet/encuesta/intranet_addencuesta.php','','frame_principal','Y','N','N','','osalazar','2008-08-28 13:38:08',NULL);
INSERT INTO `modulo` VALUES (374,28,340,'N','1','sarconsrecaudacion','Recaudación Por Delegación','./gerencial/consulta/recaudacion_delegacion/sareta_consrecaudacion.php','','frame_principal','Y','N','N','','osalazar','2008-09-01 13:47:40',NULL);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
